### PR TITLE
Update the document for installation

### PR DESCRIPTION
**Pull request by himkt**
I have updated the documentation for installation.
- support Python3.x
- support gcc-c++<=5.5

### CODE REVIEW

**Comment by eiichiroi** [comment]
Thank you!

Please fix the version of python to '2.5 〜 3.5' according to [the waf's requirement](https://waf.io/book/#_getting_the_waf_file).
The waf require cPython 2.5 to 3.5, Pypy or Jython >= 2.5.

**Comment by himkt** [comment]
@eiichiroi Thanks, I updated.
Do you think we have to write about PyPy and Jython here?

**Comment by eiichiroi** [comment]
It's nice, please.

**Comment by eiichiroi** [comment]
Let's make it a future work.

**Pull request merged**
